### ISSUE TITLE
Nodge/EAuth Google Oauth2 Stopped Working

### ISSUE THREAD

**Issue by Juanfcomoraless** [Nodge/yii2-eauth#122]
### What steps will reproduce the problem?
Authentication to Yii2 with Google OAuth2 using nodge/eauth
### What's expected?
Successful login
### What do you get instead?
> EAuthException: Error in retrieving token: "redirect_uri_mismatch"

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.5
| Yii Auth Client version | 2.0
| Yii HTTP Client version |
| PHP version             | 5.4
| Operating system        | Debian 7.2 (AMD64)

1. We has not updated the code from our websites
2. We have the same problem in all servers (with Debian 7.2)
3. We create Google API project, client, etc. was created, under a different Google Developer console account, same result

Thanks.

**Comment by demimurych** [comment]
I also had the same problem.

**Comment by Rjgoolsby** [comment]
Same here. If anyone figures out a fix please share. I'll be working on this all day today unfortunately

**Comment by demimurych** [comment]
I found where the error is.
Redirect URl and callback URL should be the same.

Dirty fix - 
/var/www/heaven/vendor/nodge/yii2-eauth/src/oauth2/Service.php
add "scope" in to filter aparametres (see bold)

It was 
foreach (['code', 'state', 'redirect_uri'] as $param) {

has become
foreach (['code', 'state', 'redirect_uri'**, 'scope']** as $param) {



```
protected function getCallbackUrl()
	{
           
        
			$url = $_GET['redirect_uri'];
		}
		else {
			$route = Yii::$app->getRequest()->getQueryParams();
			array_unshift($route, '');

			// Can not use these params in OAuth2 callbacks
			foreach (['code', 'state', 'redirect_uri', 'scope'] as $param) {
				if (isset($route[$param])) {
					unset($route[$param]);
				}
			}

			$url = Url::to($route, true);
		}

        
		return $url;
	}
```

**Comment by Juanfcomoraless** [comment]
> I found where the error is.
> Redirect URl and callback URL should be the same.
> 
> Dirty fix -
> /var/www/heaven/vendor/nodge/yii2-eauth/src/oauth2/Service.php
> add "scope" in to filter aparametres (see bold)
> 
> It was
> foreach (['code', 'state', 'redirect_uri'] as $param) {
> 
> has become
> foreach (['code', 'state', 'redirect_uri'**, 'scope']** as $param) {
> 
> ```
> protected function getCallbackUrl()
> 	{
>            
>         
> 			$url = $_GET['redirect_uri'];
> 		}
> 		else {
> 			$route = Yii::$app->getRequest()->getQueryParams();
> 			array_unshift($route, '');
> 
> 			// Can not use these params in OAuth2 callbacks
> 			foreach (['code', 'state', 'redirect_uri', 'scope'] as $param) {
> 				if (isset($route[$param])) {
> 					unset($route[$param]);
> 				}
> 			}
> 
> 			$url = Url::to($route, true);
> 		}
> 
>         
> 		return $url;
> 	}
> ```

Thank you so much Master, Its works for me.

**Comment by Juanfcomoraless** [comment]
Thank you so much Master, Its works for me.

**Comment by Juanfcomoraless** [comment]
Thank you so much Master, Its works for me.

**Comment by Rjgoolsby** [comment]
You beat me to it :-). 

I had narrowed it down to the Http Client request body. I didn't get as far as you. Great job @demimurych.

Do anyone know if this project is still maintained? Are you going to submit a pull request or should I?

**Comment by Rjgoolsby** [comment]
ACTUALLY There's already a pull request for this https://github.com/Nodge/yii2-eauth/pull/120. I don't know if this project is maintained anymore. @Nodge are you still the maintainer for this? This is a pretty critical PR.
