### ISSUE TITLE
Setting read-only property: common\models\User::authKey

### ISSUE THREAD

**Issue by iMihael** [Nodge/yii2-eauth#31]
I catch an error when start oauth process: 

Invalid Call – yii\base\InvalidCallException

Setting read-only property: common\models\User::authKey

**Comment by lgXenos** [comment]
have this
maybe need add to installation guide. 
possible appear in yii2-advanced

**Comment by evgenii888k** [comment]
Yes, please add to installation guide. And notify me.Thx
>
>
>have this
>maybe need add to installation guide. 
>possible appear in yii2-advanced 
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or  view it on GitHub


С уважением,

gud3ik@mail.ru

**Comment by feeland** [comment]
Maybe you disorder authKey and authkey
