### ISSUE TITLE
When creating Google API Client ID, what should redirect URI be?

### ISSUE THREAD

**Issue by jones6951** [Nodge/yii2-eauth#35]
I am trying to get this working, but not having any luck.

I've created a Google Client ID, where I get the Client ID, Secret etc. What should the redirect URI value be?

I've tried various things, but clicking on the Google connect button on my login page results in a popup with Page not found error.

Edit: Figured it out, but it may be nice to make some mention of it in the documentation. e.g. Set the Redirect URI to your login page.

**Comment by drew1two** [comment]
Did you need to add the query string of "?service=google_oauth" as well?
I cannot get this working with google at all.

I've bound a site to 127.0.0.1 in my hosts file.
This is a copy of my live site 
eg:- 
actual live site (has exactly this path as well)
mysite.com/login/

host file
127.0.0.1 mysite.com

local yii2 app now called mysite.com and works fine.

facebook works perfect
Google console has these setting:-
redirect URI's:-
http://mysite.com/login/
http://mysite.com/signup/

I've tried these with and without the last slash, also tried with the querystring as well.

any ideas?
Thanx in advance.

**Comment by Nodge** [comment]
There is the `redirect_uri` query param in URL of popup window. You need to copy it if you dont know your redirect URI.
For example, for [demo app](http://nodge.ru/yii-eauth/demo2) `redirect_uri` is: `http://nodge.ru/yii-eauth/demo2/login/google_oauth`.
