### ISSUE TITLE
How to custom scope

### ISSUE THREAD

**Issue by lhviet** [Nodge/yii2-eauth#38]
Hi, I want to get email from Google oauth2 but don't know how to achieve it.

May you help me?

Thank you very much.

**Comment by maximal** [comment]
What was the problem in?

**Comment by lhviet** [comment]
I solved it.
Just change $scopes in GoogleOAuth2Service.php.
However, I think it is better if we can custom it at config file. I don't wanna change source code of extension.

**Comment by maximal** [comment]
Maybe we shouldn’t close the issue then? It leaves space for extending extension configuration.

**Comment by lhviet** [comment]
Haha, maybe, you're right :+1:

**Comment by maximal** [comment]
Or at least add a couple of lines to documentation.

**Comment by con322** [comment]
Did you manager to get the email? If so i'd be interested to know how :)

**Comment by Nodge** [comment]
There is no need to change the extension source code for that. You should [extend base classes](https://github.com/Nodge/yii2-eauth#extending). Example can be found in [/src/services/extended](https://github.com/Nodge/yii2-eauth/tree/master/src/services/extended).
