### ISSUE TITLE
facebook deprecated

### ISSUE THREAD

**Issue by iMihael** [Nodge/yii2-eauth#39]
When login via facebook I catch an error:
>>You must upgrade this app to Graph API v2.x
>>v1.0 will be deprecated on April 30, 2015
>>Learn how to upgrade

please, fix this.

**Comment by mipapo** [comment]
@iMihael When you get that message?

**Comment by iMihael** [comment]
When redirected to facebook. Here a screenshot https://qsnapnet.com/snaps/m7ev1gy36zf9wwm
sorry, my facebook is on russian lang, but you can see the notification.

**Comment by msvmsvmsvmsv** [comment]
I too get this msg: 

You must upgrade this app to Graph API v2.x
v1.0 will be deprecated on April 30, 2015
Learn how to upgrade

**Comment by Nodge** [comment]
The extension is ready to work with API v2.x.
But your application may be affected by breaking changes in API. So read the [upgrade guide](https://developers.facebook.com/docs/apps/upgrading) and then turn on the migration in facebook application settings.
