### ISSUE TITLE
Does social login/register work on localhost?

### ISSUE THREAD

**Issue by con322** [Nodge/yii2-eauth#41]
Might be a bit of a noob question but does social login/register work on MAMP localhost?

Currently I have it setup for twitter google and facebook neither of them work.

Twitter I get - EAuthException: Error in retrieving token.
Facebook I get - Setting read-only property: common\models\User::authKey
Google I get - Error: redirect_uri_mismatch

Update I forgot to add 

    public $authKey;

**Comment by izzat4441** [comment]
I have exactly that problem now : )
