### ISSUE TITLE
yii2 get full data/response from service 

### ISSUE THREAD

**Issue by con322** [Nodge/yii2-eauth#42]
Great extension by the way.

I was wondering in the demo project the data/response you get after logging in is greater than what I get.

For example the only data I get is id, name, url and service.

For example facebook on the demo you receive everything education, email, DOB etc

**Comment by ashokkumarjuly** [comment]
First of all thanks for this great module,
@con322 , In my case  i get the "email" field from response, by 
adding the below line on fetchAttributes() in yii2-eauth/src/services/FacebookOAuth2Service.php
$this->attributes['email'] = $info['email'];
 so i go the value of the email field  in "profile" property of response object.

**Comment by Nodge** [comment]
You should extend base classes to fetch additional data. For example: [FacebookOAuth2Service.php](https://github.com/Nodge/yii2-eauth/blob/master/src/services/extended/FacebookOAuth2Service.php)

**Comment by jasonhai** [comment]
Hi Nodge,

I dont know this is the problem by me or not. But when I extended FacebookOAuth2Service.php, I saw that, It's full grant to get user info, email, dob ... But when I fetchAttributes. I always get only ID and Name info. Can we have another way to get it?

Thanks all for your help. I'm stuck in this step .
