### ISSUE TITLE
how get pic_square in facebook

### ISSUE THREAD

**Issue by missjewel** [Nodge/yii2-eauth#45]
how get a profile photo in facebook using this extension?

**Comment by zckri** [comment]
<img src="http://graph.facebook.com/<?=$facebook_user_id?>/picture" />

**Comment by missjewel** [comment]
thanks, if i want other dimensiones the image, i.e small, large, medium ?

**Comment by zckri** [comment]
https://graph.facebook.com/USER_ID/picture?width=590&height=600

you're welcome

**Comment by missjewel** [comment]
thanks. I work it.

**Comment by Tiberi-ym** [comment]
Thanks, zckri - you answer helped me too) But very interesting - why facebook no return photo, even request parapms is correct. I get it this method:
protected function fetchAttributes()
	{
		$info = $this->makeSignedRequest('me',array(
			'query' => array(
				'fields' => 'email, name, birthday, photos, gender, link, first_name, last_name, age_range',
			),
		));
                print_r($info);exit();
      }
and facebook return all - but no photo.
P.S. 
On first -  I try to wrire: 
protected $scopes = array(self::SCOPE_EMAIL,self::SCOPE_USER_PHOTOS,self::SCOPE_USER_BIRTHDAY);
but it's no work - facebook return just name and id. Just set 'fields' property - is helped

**Comment by asratnani** [comment]
yes i have faced same problem please help me..

**Comment by Tiberi-ym** [comment]
Exist another way to take photo. You must use URL: https://graph.facebook.com/USER_ID/picture?width=56&height=56 (you can set size what you need).
So, now i use:
protected function fetchAttributes()
	{
		$info = $this->makeSignedRequest('me',array(
			'query' => array(
				'fields' => 'email, name, birthday, gender, link, first_name, last_name, age_range',
			),
		));

		$this->attributes['id'] = $info['id'];
		........
		$this->attributes['photo'] = 'https://graph.facebook.com/'.$info['id'].'/picture?width=56&height=56';
			
		return true;
	}

**Comment by Nodge** [comment]
Example: https://github.com/Nodge/yii2-eauth/commit/ea07693e8ca5e4dab8a9360e99307fdd855004ea
