### ISSUE TITLE
How get email in facebook ?

### ISSUE THREAD

**Issue by missjewel** [Nodge/yii2-eauth#46]
Wich is the line for I get a email with this extension?

**Comment by missjewel** [comment]
Already solved it

**Comment by sanjarbek** [comment]
@missjewel can you please provide a code how you solve getting email in facebook?
What did I do to get email. 
Override protected $scopes = array(self::SCOPE_EMAIL);
in my own class inherited from faceboooauth2 class.
 protected function fetchAttributes()
    {
            $info = $this->makeSignedRequest('me');

            $this->attributes['id'] = $info['id'];
            $this->attributes['name'] = $info['name'];
            $this->attributes['url'] = $info['link'];
            $this->attributes['email'] = $info['email'];

            return true;
   }

But I constantly get error there is not link and email.

**Comment by Myrkotyn** [comment]
@sanjarbek have you decided your problem? I have same problem.

**Comment by vladarta** [comment]
same problem, user default extended service \vendor\nodge\yii2-eauth\src\services\extended\FacebookOAuth2Service.php - no result.
Please help.

**Comment by Nodge** [comment]
Starting from version 2.4 Graph API requires that you explicitly request the fields you need for your GET requests.
I've updated example here: https://github.com/Nodge/yii2-eauth/blob/a00e9d5652eb2be57e08bf04be17e9e4d5db61bf/src/services/extended/FacebookOAuth2Service.php

**Comment by leonardojulius** [comment]
hey how may I Update on Git? can't detect git add . the on vendors. Cant find specific Fix on Google. only thing is to remove the gitignore but it upload all vendors aw:( takes to long and free account on heroku pls guide me
