### ISSUE TITLE
TokenDefaultLifetime is misinterpreted in ServiceProxy

### ISSUE THREAD

**Issue by ertong** [Nodge/yii2-eauth#53]
[ServiceProxy.php:165] $token->setLifetime($this->service->getTokenDefaultLifetime());

The default value for $tokenDefaultLifetime in ServiceBase is TokenInterface::EOL_UNKNOWN=-9001.
This value can be returned by $this->service->getTokenDefaultLifetime().

If this value is passed to $token->setLifetime, the end of life will be set by
[AbstractToken.php:108]:  $this->endOfLife = intval($lifetime) + time();
which will be time()-9001, which is wrong.

I've faced this issue with facebook authentication recently.

It can be fixed by several ways:
- by changing logic around ServiceProxy.php:165
- by changing logic of AbstractToken::setLifetime (but it different package)
- by changing default value of $tokenDefaultLifetime to zero

It is hard to say which one is preferred.

**Comment by Nodge** [comment]
I've changed default token lifetime to `null`, so `AbstractToken::setLifetime` will set `endOfLife` to `EOL_UNKOWN`
