### ISSUE TITLE
How to get full info of this extension

### ISSUE THREAD

**Issue by jasonhai** [Nodge/yii2-eauth#55]
Hi Nodge!

I'm using Yii2-eauth extension, but when I try to login with facebook, I just get the name and id info. Even thought I input some value into scope like this
	protected $scopes = array(
		self::SCOPE_EMAIL,
		self::SCOPE_USER_BIRTHDAY,
		self::SCOPE_USER_HOMETOWN,
		self::SCOPE_USER_LOCATION,
		self::SCOPE_USER_PHOTOS
	);
But nothing change :(.
I'm using this function to get info: $this->makeSignedRequest('me');

Please help me show all the info of this extension.

Thank you so much!
            Jason

**Comment by maximal** [comment]
It would be better to fully describe it in the docs.

**Comment by jasonhai** [comment]
Yes, I've found it in the fully describe of this docs. Thanks @maximal

**Comment by Merisho** [comment]
The same. I don't know what to do

**Comment by Nodge** [comment]
Starting from version 2.4 Graph API requires that you explicitly request the fields you need for your GET requests.
I've updated example here: https://github.com/Nodge/yii2-eauth/blob/a00e9d5652eb2be57e08bf04be17e9e4d5db61bf/src/services/extended/FacebookOAuth2Service.php
