### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by Lord-Evil** [Nodge/yii2-eauth#57]
Facebook doesn't return "link" for some reason, so
services/FacebookOAuth2Service.php:55 can be patched as:
```
-$this->attributes['url'] = $info['link'];
+$this->attributes['url'] = "https://www.facebook.com/".$info['id'];
```

**Comment by Nodge** [comment]
`$info['link']` works ok in all of my apps. 
Can you see the link at http://nodge.ru/yii-eauth/demo2/login ?

**Comment by Lord-Evil** [comment]
Hmm.. you've got so much data of it. I only get name and id.

**Comment by Lord-Evil** [comment]
What am I doing wrong? :-)

**Comment by Nodge** [comment]
Try to use `yii2-eauth/src/services/extended/FacebookOAuth2Service.php` instead of `yii2-eauth/src/services/FacebookOAuth2Service.php` :)

**Comment by Lord-Evil** [comment]
Yeah, that's what I did.
I don't need all that info, anyway, only name and ID, but I don't understand the reason why $this->makeSignedRequest('me') doesn't return all that to me.. O.o Can it be app's persmissions?

**Comment by DarkCodius** [comment]
Try to add options to method makeSignedRequest.This code helped for me.
protected function fetchAttributes()
    {
        
        $options = [
            'query' => [
                'fields' => 'id,name,email',
            ],
        ];
        $this->attributes = $this->makeSignedRequest('me', $options);
        return true;
    }

**Comment by Nodge** [comment]
Starting from version 2.4 Graph API requires that you explicitly request the fields you need for your GET requests.
I've updated example here: https://github.com/Nodge/yii2-eauth/blob/a00e9d5652eb2be57e08bf04be17e9e4d5db61bf/src/services/extended/FacebookOAuth2Service.php
