### ISSUE TITLE
How do you change the redirect URI in the request

### ISSUE THREAD

**Issue by ramoscarlos** [Nodge/yii2-eauth#59]
I am trying to use this extension with Google OAuth2, but I get this error:
```
Error: redirect_uri_mismatch
```
I want to know, where do I specify the redirection url so I can put one that my Google Application actually allows?

I have tried with `setRedirectUrl(Url::to(['site/validUrl'])`, but it still redirects me to the `site/login` page.

Is there a way I can specify the redirect url after the login?

**Comment by Nodge** [comment]
yii-eauth always redirects to your "login" action first (ex. `SiteController::actionLogin()`)
And then it redirects to `redirectUrl` or `cancelUrl`.

If you want to change `redirect_uri` - you should change a url for your "login" action.
