### ISSUE TITLE
get an email google_oauth

### ISSUE THREAD

**Issue by rem22** [Nodge/yii2-eauth#60]
I extended fetch_attributes with 
$this->attributes['email'] = $info['email'];

Still this returns an empty email
Any ideas what am I doing wrong ?

**Comment by Nodge** [comment]
You should add email scope like this:
```
protected $scopes = [self::SCOPE_USERINFO_PROFILE, self::SCOPE_EMAIL];
```

**Comment by rem22** [comment]
Thanks, it works :D !

2015-10-17 17:28 GMT+02:00 Maxim Zemskov <notifications@github.com>:
