### ISSUE TITLE
 PHP Notice – yii\base\ErrorException  Undefined index: link in  

### ISSUE THREAD

**Issue by vladarta** [Nodge/yii2-eauth#67]
I reseave error after install ehtension plus facebook service.
Everu thing works fine till login
Please check here
http://foldbe.com/signin
![eauh error](https://cloud.githubusercontent.com/assets/7780144/11478511/1898c344-9796-11e5-99f3-3c44706b5b58.png)

**Comment by vladarta** [comment]
Temporary fixed with turning off noticies

**Comment by Nodge** [comment]
Related to #65 and #55
