### ISSUE TITLE
После авторизации через mail.ru не происходит редирект.

### ISSUE THREAD

**Issue by MatthewPattell** [Nodge/yii2-eauth#77]
Собственно говоря, если отключить опцию "авторизация через всплывающее окно" и начать авторизацию через mail.ru, сначала перекидывает на маил ру для подтверждения, а после подтверждения идет редирект на вот эту страницу:
http://connect.mail.ru/oauth/success.html?state=f4e369c0a464f3aeeda0593ba90b5e55&code=caab22e834vb81cfe71bc2923641582f
и дальше ничего не происходит. На сайт обратно не возвращает.

**Comment by frolictc** [comment]
У меня аналогичная проблема. Кто то нашел решение?
